# Generated by Django 3.2.4 on 2021-06-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, choices=[('todo', 'To Do'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='todo', help_text='Status (Todo, Ongoing, Done)', max_length=50),
        ),
    ]
